# Generated by Django 4.2.3 on 2023-07-29 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Имя')),
                ('email', models.EmailField(max_length=128, verbose_name='Почта')),
                ('Text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'question',
                'verbose_name_plural': 'Questions',
            },
        ),
    ]
